export const metadata = {
    title: "Products",
    description: "Generated by create next app",
};

export default function ProductLayout({ children }: { children: React.ReactNode; }) {
    return (
        <div className="p-10">
            {children}
        </div>
    )
}
